inherit_from: .rubocop_todo.yml
require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "config/definitions.rb"
    - "spec/dummy/**/*"

Lint/MissingSuper:
  Exclude:
    - "app/components/bs5/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Exclude:
    - "spec/**/*"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"
